### ISSUE TITLE
Production build does not work

### ISSUE THREAD

**Issue by noeRls** [solana-developers/template-react-vite-tailwind-counter#3]
Production build straight up from this project template does not work.

### Steps to reproduce

1. Install, build and serve the build
```sh
pnpm install && pnpm build && pnpm preview
```

2. Visit the displayed url in a browser

### Issue

The website does not load and there is an error in the developer console. It seems to be due to the `@solana/web3.js` package.
```
Uncaught ReferenceError: Cannot access 'Vi' before initialization
    at solanaWeb3-CMm85vn2.js:1:3377
```

**Comment by beeman** [comment]
Thanks for creating this issue @noeRls! This should now be fixed with this patch https://github.com/solana-developers/template-react-vite-tailwind-counter/commit/d57dd620e36257b74cbb36135a988c7b800099c1!

**Comment by noeRls** [comment]
Thanks for your fix!
